# Documentation: https://github.com/compose-spec/compose-spec/blob/master/spec.md
# Purpose: Build local containers for the Mutillidae environment

version: '3.7'
services:

  database:
    container_name: database
    image: webpwnized/mutillidae:database
    build: 
        context: ./database
        dockerfile: Dockerfile
    networks:
      - datanet   

  database_admin:
    container_name: database_admin
    depends_on:
      - database
    image: webpwnized/mutillidae:database_admin
    build:
        context: ./database_admin
        dockerfile: Dockerfile
    ports:
      - 127.0.0.1:81:80
    networks:
      - datanet   

  www:
    container_name: www
    depends_on:
      - database
      - directory
    image: webpwnized/mutillidae:www
    build:
        context: ./www
        dockerfile: Dockerfile
    ports:
      - 127.0.0.1:80:80
      - 127.0.0.1:443:443
    networks:
      - datanet
      - ldapnet

  directory:
    container_name: directory
    image: webpwnized/mutillidae:ldap
    build:
        context: ./ldap
        dockerfile: Dockerfile
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d
    ports:
      - 127.0.0.1:389:389
    networks:
      - ldapnet

  directory_admin:
    container_name: directory_admin
    depends_on:
      - directory
    image: webpwnized/mutillidae:ldap_admin
    build:
        context: ./ldap_admin          
        dockerfile: Dockerfile
    ports:
      - 127.0.0.1:82:80
    networks:
      - ldapnet

# Volumes to persist data used by the LDAP server
volumes:
  ldap_data:
  ldap_config:
  
# Create network segments for the containers to use
networks:
    datanet:
    ldapnet:
